Repository Teamie-UMC-8th/Teamie-server, pull requests merged in 2025-08, with the labels that each got.

#171 [Refactor] 프로젝트 참여 응답 수정, 에러 세분화
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/modules/projects/dtos/create-project.dto.ts
  src/modules/projects/dtos/join-project.dto.ts
  src/modules/projects/dtos/validate-invite.dto.ts
  src/modules/projects/projects.controller.ts
  src/modules/projects/projects.service.ts
Labels: :recycle: refactor

#173 [Fix] 프로젝트 완료 시 참여코드도 만료, 트랜잭션 오류 해결
  src/modules/master-portfolios/master-portfolios.service.ts
  src/modules/projects/projects.service.ts
Labels: :bug: fix

#175 [Feat] 회의록 선택 기능 추가 및 질문 생성에 실제 데이터 사용
  src/infra/llm/llm.service.ts
  src/modules/comments/comments.entity.ts
  src/modules/mappings/attendees/attendees.entity.ts
  src/modules/mappings/managers/managers.entity.ts
  src/modules/mappings/task-files/task-files.entity.ts
  src/modules/mappings/task-files/task-files.module.ts
  src/modules/mappings/task-files/task-files.service.ts
  src/modules/mappings/writers/writers.entity.ts
  src/modules/master-portfolios/dtos/create-questions.dto.ts
  src/modules/master-portfolios/master-portfolios.controller.ts
  src/modules/master-portfolios/master-portfolios.module.ts
  src/modules/master-portfolios/master-portfolios.service.ts
  src/modules/plans/dtos/create-plan.dto.ts
  src/modules/plans/dtos/plan-details.dto.ts
  src/modules/plans/entities/plan.entity.ts
  src/modules/plans/plans.controller.spec.ts
  src/modules/plans/plans.module.ts
  src/modules/plans/plans.service.spec.ts
  src/modules/plans/plans.service.ts
  src/modules/projects/entities/projects.entity.ts
  src/modules/steps/entities/steps.entity.ts
  src/modules/steps/steps.module.ts
  src/modules/steps/steps.service.ts
  src/modules/tasks/dtos/get-task.dto.ts
  src/modules/tasks/dtos/task-dashboard-status-view-dto.ts
  src/modules/tasks/dtos/task-dashboard-step-view-dto.ts
  src/modules/tasks/dtos/update-task.dto.ts
  src/modules/tasks/entities/tasks.entity.ts
  src/modules/tasks/tasks.module.ts
  src/modules/tasks/tasks.service.ts
Labels: :sparkles: feature

#186 [Feat] CORS 다중 origin 지원 및 쿼리 파라미터 redirect_url에 대한 리다이렉트 지원
  package-lock.json
  package.json
  src/main.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/guards/set-redirect-url.guard.ts
  src/modules/auth/strategies/kakao.strategy.ts
Labels: :sparkles: feature

#185 [Feat] 선택 가능한 회의록 조회 api 구현
  src/modules/master-portfolios/dtos/selectable-plan.dto.ts
  src/modules/master-portfolios/master-portfolios.controller.ts
  src/modules/master-portfolios/master-portfolios.module.ts
  src/modules/master-portfolios/master-portfolios.service.ts
Labels: :sparkles: feature

#187 [Feat] 일정 삭제 기능 구현
  src/modules/plans/dtos/delete-plan.dto.ts
  src/modules/plans/plans.controller.ts
  src/modules/plans/plans.service.ts
Labels: :sparkles: feature

#182 [Feat] 팀 캘린더 조회 기능 구현
  src/common/dtos/calender-date-query.dto.ts
  src/common/enums/calender-card-type.enum.ts
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/modules/plans/plans.service.ts
  src/modules/projects/dtos/team-calender-response.dto.ts
  src/modules/projects/projects.controller.ts
  src/modules/projects/projects.module.ts
  src/modules/projects/projects.service.ts
  src/modules/tasks/tasks.module.ts
  src/modules/tasks/tasks.service.ts
Labels: :sparkles: feature

#189 [Fix] 프로젝트 참여, 코드 유효성 검사 오류 해결과 엔티티 수정
  package-lock.json
  package.json
  src/modules/projects/entities/projects.entity.ts
  src/modules/projects/projects.service.ts
Labels: :bug: fix

#188 [Refactor] 업무 대시보드, updateTask 수정
  src/modules/tasks/dtos/task-dashboard-status-view-dto.ts
  src/modules/tasks/dtos/task-dashboard-step-view-dto.ts
  src/modules/tasks/tasks.service.ts
Labels: :recycle: refactor

#199 [Feat] 나의 업무 대시보드 조회 기능 구현
  src/common/dtos/user-profile.dto.ts
  src/modules/plans/dtos/plan-details.dto.ts
  src/modules/tasks/dtos/user-task.dto.ts
  src/modules/tasks/tasks.controller.ts
  src/modules/tasks/tasks.module.ts
  src/modules/tasks/tasks.service.ts
  src/modules/users/dtos/user-project.dto.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
Labels: :sparkles: feature

#201 [Feat] AI 첨삭 생성 API 구현
  package-lock.json
  package.json
  src/app.module.ts
  src/infra/llm/llm.service.ts
  src/infra/llm/schemas/portfolio-correction.schema.ts
  src/modules/final-portfolios/final-portfoilos.service.ts
  src/modules/final-portfolios/final-portfolios.controller.ts
  src/modules/final-portfolios/final-portfolios.module.ts
  src/modules/final-portfolios/portfolio-ai-result/portfolio-ai-results.entity.ts
  src/modules/portfolio-corrections/dtos/correction-field.dto.ts
  src/modules/portfolio-corrections/dtos/correction-line.dto.ts
  src/modules/portfolio-corrections/dtos/create-corrections.dto.ts
  src/modules/portfolio-corrections/dtos/user-portfolio-correction-response.dto.ts
  src/modules/portfolio-corrections/entities/ai-correction.entity.ts
  src/modules/portfolio-corrections/entities/portfolio-correction.entity.ts
  src/modules/portfolio-corrections/entities/rag-data.entity.ts
  src/modules/portfolio-corrections/portfolio-corrections.controller.ts
  src/modules/portfolio-corrections/portfolio-corrections.module.ts
  src/modules/portfolio-corrections/portfolio-corrections.service.ts
  src/modules/users/entities/users.entity.ts
Labels: :sparkles: feature

#216 [Feat] 프로젝트 참여자 리스트 조회
  src/modules/projects/projects.controller.ts
  src/modules/projects/projects.service.ts
Labels: :sparkles: feature

#208 [Feat] 마스터 포트폴리오에 status 추가 및 상태 업데이트 코드 추가
  src/common/enums/master-portfolio-status.enum.ts
  src/modules/master-portfolios/entities/master-portfolios.entity.ts
  src/modules/master-portfolios/master-portfolios.controller.ts
  src/modules/master-portfolios/master-portfolios.service.ts
Labels: :sparkles: feature

#213 [Fix] 일정 수정/권한 체크 및 업데이트 로직 수정
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/modules/plans/plans.service.ts
  src/modules/portfolio-corrections/portfolio-corrections.service.ts
  src/modules/projects/projects.service.ts
Labels: :bug: fix

#222 [Fix] 개인회고 업데이트 API 작동하도록 DTO 수정
  src/modules/personal-recalls/dtos/update-personal-recall.dto.ts
Labels: :bug: fix

#223 [Feat] AI 첨삭 진행 상태 기능 추가
  src/common/enums/portfolio-correction-status.enum.ts
  src/modules/portfolio-corrections/entities/portfolio-correction.entity.ts
  src/modules/portfolio-corrections/portfolio-corrections.controller.ts
  src/modules/portfolio-corrections/portfolio-corrections.service.ts
Labels: :sparkles: feature

#230 [Refactor] 프로젝트 구조 변경 (repository, entities)
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/services/auth.service.ts
  src/modules/comments/cocomments/cocomments.controller.ts
  src/modules/comments/cocomments/cocomments.module.ts
  src/modules/comments/cocomments/dto/create-cocomment.dto.ts
  src/modules/comments/cocomments/dto/update-cocomment.dto.ts
  src/modules/comments/cocomments/entities/cocomments.entity.ts
  src/modules/comments/cocomments/repositories/cocoment.repository.ts
  src/modules/comments/cocomments/services/cocomments.service.ts
  src/modules/comments/comments.controller.ts
  src/modules/comments/comments.module.ts
  src/modules/comments/dto/create-comment.dto.ts
  src/modules/comments/dto/get-comment.dto.ts
  src/modules/comments/dto/update-comment.dto.ts
  src/modules/comments/entities/comments.entity.ts
  src/modules/comments/repositories/comments.repository.ts
  src/modules/comments/services/comments.service.ts
  src/modules/master-portfolios/master-portfolios.controller.ts
  src/modules/master-portfolios/master-portfolios.module.ts
  src/modules/master-portfolios/repositories/master-portfolios.repository.ts
  src/modules/master-portfolios/services/master-portfolios.service.ts
  src/modules/personal-recalls/personal-recalls.controller.ts
  src/modules/personal-recalls/personal-recalls.module.ts
  src/modules/personal-recalls/repositories/personal-recalls.repository.ts
  src/modules/personal-recalls/services/personal-recalls.service.ts
  src/modules/plans/gateways/plans.gateway.ts
  src/modules/plans/plans.controller.ts
  src/modules/plans/plans.module.ts
  src/modules/plans/repositories/plan.repository.ts
  src/modules/plans/services/plans.service.spec.ts
  src/modules/plans/services/plans.service.ts
  src/modules/portfolio-corrections/portfolio-corrections.controller.ts
  src/modules/portfolio-corrections/portfolio-corrections.module.ts
  src/modules/portfolio-corrections/repositories/portfolio-correction.repository.ts
  src/modules/portfolio-corrections/services/portfolio-corrections.service.ts
  src/modules/projects/dtos/all-project-response.dto.ts
  src/modules/projects/dtos/project-response.dto.ts
  src/modules/projects/projects.controller.ts
  src/modules/projects/projects.module.ts
  src/modules/projects/repositories/project.repository.ts
  src/modules/projects/services/projects.service.ts
  src/modules/steps/repositories/step.repository.ts
  src/modules/steps/services/steps.service.ts
  src/modules/steps/steps.controller.ts
  src/modules/steps/steps.module.ts
  src/modules/tasks/entities/tasks.entity.ts
  src/modules/tasks/repositories/task.repository.ts
  src/modules/tasks/services/tasks.service.ts
  src/modules/tasks/tasks.controller.ts
  src/modules/tasks/tasks.module.ts
  src/modules/users/entities/users.entity.ts
  src/modules/users/repositories/user.repository.ts
  src/modules/users/services/users.service.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
Labels: :recycle: refactor

#236 [Docs] 코파일럿 코드리뷰용 프롬프트 파일 내용 추가
  .github/copilot-instructions.md
Labels: :memo: docs

#238 [Feat] RAG 분리 및 제목 저장 추가
  src/infra/llm/llm.module.ts
  src/infra/llm/llm.service.ts
  src/infra/llm/rag.service.ts
  src/modules/portfolio-corrections/entities/rag-data.entity.ts
  src/modules/portfolio-corrections/services/portfolio-corrections.service.ts
Labels: :sparkles: feature

#241 [Fix] 마스터 포트폴리오 조회 API 응답 수정
  src/modules/master-portfolios/dtos/master-portfolio-response.dto.ts
  src/modules/master-portfolios/services/master-portfolios.service.ts
Labels: :bug: fix

#246 [Feat] 마스터 포트폴리오 AI 생성 결과 구조 검사 기능 추가
  src/modules/master-portfolios/services/master-portfolios.service.ts
  src/modules/portfolio-corrections/services/portfolio-corrections.service.ts
Labels: :sparkles: feature

#248 [Fix] RAG 결과 저장 엔티티의 link 속성 타입 변경
  src/modules/portfolio-corrections/entities/rag-data.entity.ts
Labels: :bug: fix

#250 [Refactor] 업무 생성 service로직 수정
  src/modules/tasks/services/tasks.service.ts
Labels: :recycle: refactor

#254 [Feat] 이벤트 pub/sub 토대 구현
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.module.ts
  src/common/dtos/event-payload.dto.ts
  src/common/response/real-time-response.dto.ts
  src/infra/event-bus/event-bus.module.ts
  src/infra/event-bus/event-bus.service.spec.ts
  src/infra/event-bus/event-bus.service.ts
  src/modules/plans/listener/plans.listener.ts
  src/modules/plans/plans.controller.spec.ts
  src/modules/plans/plans.module.ts
  src/modules/plans/services/plans.service.spec.ts
  src/modules/plans/services/plans.service.ts
  src/modules/plans/test/plans.listener.spec.ts
  src/modules/steps/listener/steps.listener.ts
  src/modules/tasks/listener/tasks.listener.ts
Labels: :sparkles: feature

#242 [Refactor] 서비스/컨트롤러 리팩토링, 컨트롤러 수정 (Project)
  src/common/exceptions/custom.errors.ts
  src/config/typeorm.config.ts
  src/modules/auth/guards/project-member.guard.ts
  src/modules/master-portfolios/services/master-portfolios.service.ts
  src/modules/plans/services/plans.service.ts
  src/modules/projects/dtos/all-project-response.dto.ts
  src/modules/projects/dtos/change-leader.dto.ts
  src/modules/projects/dtos/complete-project.dto.ts
  src/modules/projects/dtos/create-post.dto.ts
  src/modules/projects/dtos/join-project.dto.ts
  src/modules/projects/dtos/project-response.dto.ts
  src/modules/projects/dtos/update-profile.dto.ts
  src/modules/projects/dtos/update-project.dto.ts
  src/modules/projects/dtos/user-with-task.dto.ts
  src/modules/projects/entities/projects.entity.ts
  src/modules/projects/entities/userProjects.entity.ts
  src/modules/projects/projects.controller.ts
  src/modules/projects/projects.module.ts
  src/modules/projects/repositories/invite-code.store.ts
  src/modules/projects/repositories/posts.store.ts
  src/modules/projects/repositories/project.repository.ts
  src/modules/projects/repositories/user-project.repository.ts
  src/modules/projects/services/projects.service.ts
  src/modules/steps/dtos/update-task-step.dto.ts
  src/modules/tasks/services/tasks.service.ts
  src/modules/tasks/tasks.module.ts
  src/modules/users/entities/users.entity.ts
  src/modules/users/services/users.service.ts
  src/modules/users/users.module.ts
Labels: :recycle: refactor

#262 [Feat] 구독 모델의 웹소켓 게이트웨이 구현
  src/app.module.ts
  src/common/enums/sub-event-type.enum.ts
  src/common/exceptions/ws-exception.filter.ts
  src/common/utils/cookie.parse.ts
  src/config/app.config.ts
  src/infra/gateway/app.gateway.spec.ts
  src/infra/gateway/app.gateway.ts
  src/infra/gateway/dtos/subscribe-payload.dto.ts
  src/infra/gateway/gateway.module.ts
  src/main.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/guards/ws-auth.guard.ts
  src/modules/auth/strategies/jwt.strategy.ts
  src/modules/plans/gateways/plans.gateway.ts
  src/modules/plans/listener/plans.listener.spec.ts
  src/modules/plans/listener/plans.listener.ts
  src/modules/plans/plans.module.ts
  src/modules/plans/services/plans.service.ts
Labels: :sparkles: feature

#265 [Docs] AI 첨삭 Swagger 작성
  src/modules/portfolio-corrections/dtos/company-insight-response.dto.ts
  src/modules/portfolio-corrections/dtos/correction-result.dto.ts
  src/modules/portfolio-corrections/dtos/portfolio-correction-response.dto.ts
  src/modules/portfolio-corrections/dtos/rag-response.dto.ts
  src/modules/portfolio-corrections/dtos/status-response.dto.ts
  src/modules/portfolio-corrections/portfolio-corrections.controller.ts
  src/modules/portfolio-corrections/services/portfolio-corrections.service.ts
Labels: :memo: docs

#252 [Refactor] 서비스/레포지토리 분리 및 컨트롤러 수정 (Comment, Cocoment, TaskFile)
  src/modules/comments/cocomments/cocomments.controller.ts
  src/modules/comments/cocomments/cocomments.module.ts
  src/modules/comments/cocomments/repositories/cocoment.repository.ts
  src/modules/comments/cocomments/services/cocomments.service.ts
  src/modules/comments/comments.module.ts
  src/modules/comments/repositories/comments.repository.ts
  src/modules/comments/services/comments.service.ts
  src/modules/mappings/task-files/task-files.controller.ts
  src/modules/mappings/task-files/task-files.module.ts
  src/modules/mappings/task-files/task-files.service.ts
  src/modules/tasks/services/tasks.service.ts
  src/modules/tasks/tasks.controller.ts
Labels: :recycle: refactor

#266 [Fix] task의 step 이동 버그 수정
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/modules/steps/repositories/step.repository.ts
  src/modules/steps/services/steps.service.ts
  src/modules/steps/steps.controller.ts
  src/modules/steps/steps.module.ts
  src/modules/tasks/repositories/task.repository.ts
  src/modules/tasks/services/tasks.service.ts
  src/modules/tasks/tasks.module.ts
Labels: :bug: fix

#240 [Refactor] 서비스/레포지토리 분리 및 컨트롤러 수정 (User, Plan)
  src/modules/auth/auth.controller.ts
  src/modules/master-portfolios/master-portfolios.controller.ts
  src/modules/master-portfolios/services/master-portfolios.service.ts
  src/modules/plans/entities/attendees.entity.ts
  src/modules/plans/entities/plan.entity.ts
  src/modules/plans/entities/writers.entity.ts
  src/modules/plans/plans.controller.ts
  src/modules/plans/plans.module.ts
  src/modules/plans/repositories/attendees.repository.ts
  src/modules/plans/repositories/plan.repository.ts
  src/modules/plans/repositories/writers.repository.ts
  src/modules/plans/services/plans.service.ts
  src/modules/portfolio-corrections/portfolio-corrections.controller.ts
  src/modules/projects/dtos/all-project-response.dto.ts
  src/modules/projects/dtos/user-with-task.dto.ts
  src/modules/projects/entities/projects.entity.ts
  src/modules/projects/projects.controller.ts
  src/modules/projects/projects.module.ts
  src/modules/projects/services/projects.service.ts
  src/modules/projects/user-projects/entities/user-projects.entity.ts
  src/modules/projects/user-projects/repositories/user-project.repository.ts
  src/modules/projects/user-projects/user-project.module.ts
  src/modules/tasks/services/tasks.service.ts
  src/modules/tasks/tasks.module.ts
  src/modules/users/entities/users.entity.ts
  src/modules/users/repositories/user.repository.ts
  src/modules/users/services/users.service.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
Labels: :recycle: refactor

#281 [Refactor] 업무 상세 조회 responseDto수정
  src/modules/tasks/dtos/get-task.dto.ts
  src/modules/tasks/task-files/dtos/create-task-files.dto.ts
Labels: :recycle: refactor

#282 [Feat] AI 첨삭 결과 개별 조회 API 추가
  src/modules/portfolio-corrections/dtos/correction-result.dto.ts
  src/modules/portfolio-corrections/portfolio-corrections.controller.ts
  src/modules/portfolio-corrections/services/portfolio-corrections.service.ts
Labels: :sparkles: feature

#286 [FEAT] 실시간 동기화 기능 구현 (PLAN)
  src/common/utils/dto-transform.ts
  src/infra/gateway/app.gateway.spec.ts
  src/infra/gateway/app.gateway.ts
  src/modules/plans/dtos/plan-details.dto.ts
  src/modules/plans/dtos/plan-payload.dto.ts
  src/modules/plans/listener/plans.listener.spec.ts
  src/modules/plans/listener/plans.listener.ts
  src/modules/plans/services/plans.service.ts
Labels: :sparkles: feature

#290 [Feat] 실시간 동기화 기능 구현 (STEP)
  src/common/response/real-time-response.dto.ts
  src/modules/projects/services/projects.service.ts
  src/modules/steps/dtos/step-payload.dto.ts
  src/modules/steps/listener/steps.listener.ts
  src/modules/steps/services/steps.service.ts
  src/modules/steps/steps.module.ts
  src/modules/tasks/dtos/update-task-status.dto.ts
  src/modules/tasks/repositories/manager.repository.ts
  src/modules/tasks/task-files/task-files.controller.ts
  src/modules/tasks/tasks.controller.ts
Labels: :sparkles: feature

#299 [Feat] 업무 파일 생성, 삭제 시 업무 상세페이지에 브로드캐스트
  src/common/response/real-time-response.dto.ts
  src/modules/tasks/services/tasks.service.ts
  src/modules/tasks/task-files/listener/task-files.listener.ts
  src/modules/tasks/task-files/repositories/task-file.repository.ts
  src/modules/tasks/task-files/task-files.module.ts
  src/modules/tasks/task-files/task-files.service.ts
Labels: :sparkles: feature

#298 [Fix] 나의 업무 API 엔드포인트 수정
  src/modules/tasks/tasks.controller.ts
  src/modules/tasks/tasks.module.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
Labels: :bug: fix

#301 [Refactor] 프롬프트 로딩 관련 코드 별도 유틸리티 함수로 분리
  src/common/utils/prompt.util.ts
  src/infra/llm/llm.service.ts
  src/infra/llm/rag.service.ts
  src/modules/master-portfolios/services/master-portfolios.service.ts
Labels: :recycle: refactor

#326 [Fix] 마스터 JWT 생성 및 로그인 관련 로직 수정
  src/common/decorators/transaction.decorator.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/guards/jwt-auth.guard.ts
  src/modules/auth/guards/set-redirect-url.guard.ts
  src/modules/auth/services/auth.service.ts
  src/modules/users/repositories/user.repository.ts
  src/modules/users/services/users.service.ts
Labels: :bug: fix

#311 [Fix] 프로젝트 에러 처리 수정
  src/common/exceptions/custom.errors.ts
  src/modules/projects/services/projects.service.ts
  src/modules/projects/user-projects/repositories/user-project.repository.ts
Labels: :bug: fix

#330 [Fix] 웹소켓 업무 브로드캐스트 payload수정
  src/modules/tasks/dtos/task-payload.dto.ts
  src/modules/tasks/services/tasks.service.ts
Labels: :bug: fix

#327 [Feat] 로그아웃 기능 구현
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/guards/jwt-auth.guard.ts
  src/modules/auth/services/auth.service.ts
  src/modules/projects/services/projects.service.ts
Labels: :sparkles: feature

#332 [Fix] 업무 검색 수정
  src/modules/tasks/repositories/task.repository.ts
  src/modules/tasks/services/tasks.service.ts
Labels: :bug: fix

#335 [Fix] 겹치는 엔드포인트 수정
  src/modules/portfolio-corrections/portfolio-corrections.controller.ts
Labels: :bug: fix

#339 [Feat] 프로젝트 종료 여부 api구현
  src/modules/projects/dtos/get-project-isCompleted.dto.ts
  src/modules/projects/projects.controller.ts
  src/modules/projects/repositories/project.repository.ts
  src/modules/projects/services/projects.service.ts
Labels: :sparkles: feature

#350 [Fix] rag 조회 데이터에 제목 추가
  src/modules/portfolio-corrections/dtos/rag-response.dto.ts
  src/modules/portfolio-corrections/services/portfolio-corrections.service.ts
Labels: :bug: fix

#349 [Fix] 나의 프로젝트 및 업무 조회 로직 수정
  src/modules/projects/user-projects/repositories/user-project.repository.ts
  src/modules/users/users.controller.ts
Labels: :bug: fix

#358 [Chore] 무중단 배포 워크플로 작성
  .github/workflows/deploy-dev.yml
  docker-compose.yml
  scripts/start.sh
  src/modules/steps/services/steps.service.ts
Labels: :wrench: chore

#362 [Feat] AI 첨삭 대상 마스터 포트폴리오 조회 API 구현
  src/common/types/master-portfolio.type.ts
  src/common/utils/transformMasterPortfolio.util.ts
  src/modules/portfolio-corrections/dtos/master-portfolio-output.dto.ts
  src/modules/portfolio-corrections/portfolio-corrections.controller.ts
  src/modules/portfolio-corrections/portfolio-corrections.module.ts
  src/modules/portfolio-corrections/services/portfolio-corrections.service.ts
Labels: :sparkles: feature

#365 [Feat] 키워드 개수 환경 변수 제거, 모든 곳에서 temperature 환경변수 도입
  src/infra/llm/llm.service.ts
  src/infra/llm/rag.service.ts
  src/infra/llm/schemas/portfolio-correction.schema.ts
  src/modules/portfolio-corrections/entities/portfolio-correction.entity.ts
  src/modules/steps/dtos/step-payload.dto.ts
  src/modules/steps/listener/steps.listener.ts
  src/modules/tasks/dtos/task-payload.dto.ts
  src/modules/tasks/enums/task-update-type.enum.ts
  src/modules/tasks/listener/tasks.listener.ts
Labels: :sparkles: feature

#368 [Fix] 포스트잇 redis 저장/삭제 수정
  src/modules/projects/repositories/posts.store.ts
  src/modules/projects/services/projects.service.ts
Labels: :bug: fix

#370 [Fix] original_content 제거 후 반환
  src/modules/portfolio-corrections/entities/portfolio-correction.entity.ts
  src/modules/portfolio-corrections/services/portfolio-corrections.service.ts
  src/modules/projects/repositories/posts.store.ts
  src/modules/projects/services/projects.service.ts
  src/modules/projects/user-projects/repositories/user-project.repository.ts
Labels: :bug: fix
