Repository Teamie-UMC-8th/Teamie-server, pull requests merged in 2025-07, with the labels that each got.

#5 [Docs] README.md 수정
  README.md
Labels: :memo: docs

#15 [Feat] 업무(Task) 생성 API 구현
  src/app.module.ts
  src/modules/tasks/dtos/create-task.dto.ts
  src/modules/tasks/tasks.controller.ts
  src/modules/tasks/tasks.entity.ts
  src/modules/tasks/tasks.module.ts
  src/modules/tasks/tasks.service.ts
Labels: :sparkles: feature

#23 [Feat] 프로젝트 홈 조회 구현
  .gitignore
  src/modules/mappings/userProjects/dto/user-with-task.dto.ts
  src/modules/projects/dto/project-response.dto.ts
  src/modules/projects/projects.controller.ts
  src/modules/projects/projects.service.ts
Labels: :sparkles: feature

#25 [Feat]: 업무 수정 API 구현
  package-lock.json
  package.json
  src/modules/mappings/managers/dtos/create-manager-dto.ts
  src/modules/mappings/taskFiles/dtos/create-taskFile-dto.ts
  src/modules/tasks/dtos/update-task.dto.ts
  src/modules/tasks/tasks.controller.ts
  src/modules/tasks/tasks.entity.ts
  src/modules/tasks/tasks.module.ts
  src/modules/tasks/tasks.service.ts
Labels: :sparkles: feature

#31 [Feat] 카카오 소셜 로그인 연결 및 회원가입 기능 구현
  package-lock.json
  package.json
  src/app.module.ts
  src/common/decorators/user.decorator.ts
  src/config/app.config.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/strategies/kakao.strategy.ts
  src/modules/comments/comments.entity.ts
  src/modules/finalPortfolios/finalPortfolios.entity.ts
  src/modules/mappings/attendees/attendees.entity.ts
  src/modules/mappings/managers/managers.entity.ts
  src/modules/mappings/projectFiles/projectFiles.entity.ts
  src/modules/mappings/taskFiles/taskFiles.entity.ts
  src/modules/mappings/userProjects/userProjects.entity.ts
  src/modules/mappings/writers/writers.entity.ts
  src/modules/masterPortfolios/masterPortfolios.entity.ts
  src/modules/personalRecalls/entities/personalRecalls.entity.ts
  src/modules/users/entities/users.entity.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
Labels: :sparkles: feature

#33 [Feat] JWT 기반 사용자 인증/인가 처리
  package-lock.json
  package.json
  src/app.module.ts
  src/common/decorators/public.decorator.ts
  src/config/app.config.ts
  src/config/swagger.config.ts
  src/main.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/guards/jwt-auth.gaurd.ts
  src/modules/auth/strategies/jwt.strategy.ts
  src/modules/healthCheck/healthCheck.controller.ts
Labels: :sparkles: feature

#36 [Refactor] userId 주입 방식 변경
  src/common/decorators/user.decorator.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/strategies/jwt.strategy.ts
  src/modules/personalRecalls/personalRecalls.controller.ts
  src/modules/projects/projects.controller.ts
  src/modules/tasks/tasks.controller.ts
  src/modules/users/users.controller.ts
Labels: :recycle: refactor

#30 [Feat] 업무 삭제 API 구현
  src/modules/tasks/dtos/delete-task.dto.ts
  src/modules/tasks/tasks.controller.ts
  src/modules/tasks/tasks.service.ts
Labels: :sparkles: feature

#40 [Refactor] 에러 메세지 구조 개선 및 책임 분리
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/custom.exception.ts
  src/common/exceptions/errorcode.enum.ts
  src/common/exceptions/http-exception.filter.ts
  src/main.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/guards/jwt-auth.gaurd.ts
  src/modules/projects/projects.controller.ts
  src/modules/projects/projects.service.ts
  src/modules/tasks/tasks.controller.ts
  src/modules/tasks/tasks.service.ts
Labels: :recycle: refactor

#39 [Feat] 프로젝트 완료 구현
  src/common/decorators/project.decorator.ts
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/common/pipes/project.pipe.ts
  src/modules/projects/dtos/complete-project.dto.ts
  src/modules/projects/projects.controller.ts
  src/modules/projects/projects.module.ts
  src/modules/projects/projects.service.ts
Labels: :sparkles: feature

#62 [Feat] 사용자 프로필 조회 API 구현
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/modules/users/dtos/user-profile.dto.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
Labels: :sparkles: feature

#68 [Fix] 배포 자동화 버그 수정
  .github/workflows/deploy-dev.yml
  src/main.ts
Labels: :bug: fix

#73 [Feat] 개인 회고 수정 API 구현
  package-lock.json
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/modules/personal-recalls/dtos/personal-recall-response.dto.ts
  src/modules/personal-recalls/dtos/update-personal-recall.dto.ts
  src/modules/personal-recalls/entities/personal-recalls.entity.ts
  src/modules/personal-recalls/personal-recalls.controller.ts
  src/modules/personal-recalls/personal-recalls.service.ts
Labels: :sparkles: feature

#87 [Refactor] LLM 호출 로직을 Infrastructure Layer로 분리
  src/common/types/question.type.ts
  src/infra/llm/formats/question-response.format.ts
  src/infra/llm/llm.module.ts
  src/infra/llm/llm.service.ts
  src/modules/master-portfolios/entities/questions.entity.ts
  src/modules/master-portfolios/master-portfolios.module.ts
  src/modules/master-portfolios/master-portfolios.service.ts
Labels: :recycle: refactor

#86 [Feat] step 수정 구현
  src/modules/steps/dtos/create-step.dto.ts
  src/modules/steps/dtos/update-step.dto.ts
  src/modules/steps/steps.controller.ts
  src/modules/steps/steps.service.ts
Labels: :sparkles: feature

#89 [Feat] 일정 상세 페이지: 게이트웨이 room 기반 구조 및 상세 정보 실시간 동기화 구현
  package-lock.json
  package.json
  src/app.module.ts
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/common/response/real-time-response.dto.ts
  src/modules/plans/dtos/plan-details.dto.ts
  src/modules/plans/gateways/plans.gateway.ts
  src/modules/plans/plans.controller.ts
  src/modules/plans/plans.entity.ts
  src/modules/plans/plans.module.ts
  src/modules/plans/plans.service.ts
  src/modules/users/entities/users.entity.ts
Labels: :sparkles: feature

#90 [Feat] 사용자 별 마스터 포트폴리오 조회 기능 구현
  src/common/response/paginated-response.dto.ts
  src/common/response/swagger-response.helper.ts
  src/modules/master-portfolios/dtos/master-portfolio-request.dto.ts
  src/modules/master-portfolios/dtos/user-master-portfolios-response.dto.ts
  src/modules/master-portfolios/master-portfolios.controller.ts
  src/modules/master-portfolios/master-portfolios.service.ts
Labels: :sparkles: feature

#99 [Docs] MasterPortfolio API 엔드포인트에 Swagger 명세 추가
  src/common/response/swagger-response.helper.ts
  src/modules/master-portfolios/dtos/master-portfolio-request.dto.ts
  src/modules/master-portfolios/dtos/master-portfolio-response.dto.ts
  src/modules/master-portfolios/master-portfolios.controller.ts
  src/modules/master-portfolios/master-portfolios.service.ts
Labels: :memo: docs

#105 [Fix] 프로젝트 완료 시 마스터포폴도 생성 추가
  src/modules/master-portfolios/master-portfolios.module.ts
  src/modules/projects/projects.module.ts
  src/modules/projects/projects.service.ts
Labels: :bug: fix

#111 [Chore] docker-compose.yml에 prompts 폴더 바인딩 추가
  docker-compose.yml
  src/modules/mappings/task-files/dtos/create-task-files.dto.ts
  src/modules/tasks/dtos/update-task.dto.ts
Labels: :wrench: chore

#101 [Feat] 마스터 포트폴리오 AI 생성 결과 저장용 테이블 생성 및 기능 추가
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/infra/llm/formats/master-portfolio-response.format.ts
  src/modules/master-portfolios/dtos/master-portfolio-ai-response.dto.ts
  src/modules/master-portfolios/dtos/update-master-portfolio.dto.ts
  src/modules/master-portfolios/entities/master-portfolio-ai.entity.ts
  src/modules/master-portfolios/master-portfolios.controller.ts
  src/modules/master-portfolios/master-portfolios.module.ts
  src/modules/master-portfolios/master-portfolios.service.ts
Labels: :sparkles: feature

#102 [Feat] 프로젝트 팀장 변경 구현
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/modules/projects/dtos/change-leader.dto.ts
  src/modules/projects/projects.controller.ts
  src/modules/projects/projects.service.ts
Labels: :sparkles: feature

#114 [Refactor] PromptLoadingException 커스텀 에러 추가
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/infra/llm/formats/question-response.format.ts
  src/infra/llm/llm.service.ts
  src/modules/master-portfolios/master-portfolios.service.ts
Labels: :recycle: refactor

#120 [Feat] Transaction Interceptor 구현 및 커스텀 데코레이터 추가
  src/app.module.ts
  src/common/decorators/transaction.decorator.ts
  src/common/interceptors/transaction.interceptor.ts
  src/modules/master-portfolios/master-portfolios.controller.ts
  src/modules/master-portfolios/master-portfolios.service.ts
Labels: :sparkles: feature

#124 [Feat] step 삭제 구현
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/modules/plans/plans.service.ts
  src/modules/projects/projects.service.ts
  src/modules/steps/entities/steps.entity.ts
  src/modules/steps/steps.controller.ts
  src/modules/steps/steps.service.ts
Labels: :sparkles: feature

#110 [Feat] 마이페이지/사용자 별 AI 첨삭 조회 기능 구현
  src/app.module.ts
  src/common/decorators/validate-iso-date.decorator.ts
  src/common/dtos/date-cursor.dto.ts
  src/modules/final-portfolios/dtos/user-final-portfolios-response.ts
  src/modules/final-portfolios/final-portfoilos.service.ts
  src/modules/final-portfolios/final-portfolios.controller.ts
  src/modules/final-portfolios/final-portfolios.entity.ts
  src/modules/final-portfolios/final-portfolios.module.ts
  src/modules/master-portfolios/dtos/user-master-portfolios-response.dto.ts
  src/modules/master-portfolios/master-portfolios.controller.ts
Labels: :sparkles: feature

#131 [Refactor] 업무 대시보드 페이징 처리
  src/modules/tasks/dtos/task-dashboard-status-view-dto.ts
  src/modules/tasks/dtos/task-dashboard-step-view-dto.ts
  src/modules/tasks/tasks.controller.ts
  src/modules/tasks/tasks.service.ts
Labels: :recycle: refactor

#125 [Feat] 웹소켓 사용자 인증 로직 구현
  src/app.module.ts
  src/common/exceptions/ws-exception.filter.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/guards/jwt-auth.guard.ts
  src/modules/auth/guards/ws-auth.guard.ts
  src/modules/master-portfolios/master-portfolios.controller.ts
  src/modules/plans/gateways/plans.gateway.ts
  src/modules/plans/plans.module.ts
Labels: :sparkles: feature

#128 [Feat] 프로필 수정 구현
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/modules/projects/dtos/all-project-response.dto.ts
  src/modules/projects/dtos/update-profile.dto.ts
  src/modules/projects/projects.controller.ts
  src/modules/projects/projects.service.ts
Labels: :sparkles: feature

#149 [Feat]: 대댓글 삭제 구현
  src/modules/comments/cocomments/cocomments.controller.ts
  src/modules/comments/cocomments/cocomments.service.ts
Labels: :sparkles: feature

#148 [Fix] 프로젝트 스웨거 응답 명세 수정
  src/modules/comments/cocomments/cocomments.controller.ts
  src/modules/projects/dtos/all-project-response.dto.ts
  src/modules/projects/dtos/create-project.dto.ts
  src/modules/projects/projects.controller.ts
  src/modules/projects/projects.service.ts
  src/modules/tasks/tasks.service.ts
Labels: :bug: fix

#143 [Fix] CORS 설정 수정 및 인증 방식 변경
  package-lock.json
  package.json
  src/config/swagger.config.ts
  src/main.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/strategies/jwt.strategy.ts
Labels: :bug: fix

#133 [Feat] 일정 생성 API 구현
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/modules/plans/dtos/create-plan.dto.ts
  src/modules/plans/plans.controller.ts
  src/modules/plans/plans.service.ts
Labels: :sparkles: feature

#156 [Chore] https 도메인 변경에 따른 쿠키 설정 변경
  src/modules/auth/auth.controller.ts
Labels: :wrench: chore

#154 [Feat] 마이페이지/사용자 프로필 수정 로직 구현
  src/common/exceptions/custom.errors.ts
  src/common/exceptions/errorcode.enum.ts
  src/infra/upload/upload.module.ts
  src/main.ts
  src/modules/auth/strategies/jwt.strategy.ts
  src/modules/comments/cocomments/cocomments.controller.ts
  src/modules/comments/cocomments/cocomments.service.ts
  src/modules/comments/dto/get-comment.dto.ts
  src/modules/tasks/tasks.controller.ts
  src/modules/tasks/tasks.service.ts
  src/modules/users/dtos/user-profile.dto.ts
  src/modules/users/entities/users.entity.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
Labels: :sparkles: feature

#159 [Refactor] swagger문서화 및 @transactional()적용
  .github/workflows/deploy-dev.yml
  src/modules/comments/cocomments/cocomments.controller.ts
  src/modules/comments/cocomments/cocomments.service.ts
  src/modules/comments/comments.controller.ts
  src/modules/comments/comments.service.ts
  src/modules/comments/dto/create-comment.dto.ts
  src/modules/tasks/dtos/create-task.dto.ts
  src/modules/tasks/dtos/get-task.dto.ts
  src/modules/tasks/dtos/update-task.dto.ts
  src/modules/tasks/tasks.controller.ts
  src/modules/tasks/tasks.entity.ts
  src/modules/tasks/tasks.service.ts
Labels: :recycle: refactor

#165 [Fix] 로그인 관련 스웨거 명세 수정
  src/config/swagger.config.ts
  src/modules/auth/auth.controller.ts
  src/modules/comments/cocomments/cocomments.controller.ts
  src/modules/comments/comments.controller.ts
  src/modules/final-portfolios/final-portfolios.controller.ts
  src/modules/master-portfolios/master-portfolios.controller.ts
  src/modules/personal-recalls/personal-recalls.controller.ts
  src/modules/plans/plans.controller.ts
  src/modules/projects/projects.controller.ts
  src/modules/steps/steps.controller.ts
  src/modules/tasks/tasks.controller.ts
  src/modules/users/users.controller.ts
Labels: :bug: fix, :memo: docs

#161 [Refactor] updateTask manager수정 시 프로젝트 참여자 확인 로직 추가
  src/modules/tasks/tasks.service.ts
Labels: :recycle: refactor
